### ISSUE TITLE
Issues with https://staging.doi.org/the-identifier/resources/factsheets/doi-resolution-documentation

### ISSUE THREAD

**Issue by wkreth** [doi-foundation/doi-website#10]
- In section 1. The link for [doi.org/10.1000/demo_DOI](http://doi.org/10.1000/demo_DOI) does not include “_DOI” in the hyperlink. (RK)

**Comment by cazinc** [comment]
Fixed in b552e14

(Although please note that the URL in question doesn't actually resolve to anything; it dumps user at DOI homepage.)
