### ISSUE TITLE
Issues with https://staging.doi.org/the-foundation/sustainability/

### ISSUE THREAD

**Issue by wkreth** [doi-foundation/doi-website#15]
* Missing Historic numbers usage image (WK)
* Missing Form 990s (WK)

**Comment by JonathanClarkDOIF** [comment]
Form 990s added, working on historic numbers (note not usage but finances) based on [this example](https://www.crossref.org/operations-and-sustainability/financials/)

**Comment by JonathanClarkDOIF** [comment]
Both done now
