### ISSUE TITLE
Partial list of pages that may need to be migrated

### ISSUE THREAD

**Issue by cazinc** [doi-foundation/doi-website#18]
This is a list of pages that we've come across while working on the site that _may_ need to be migrated to the new site. I say _may_ because it isn't clear to us if the content does actually need to come across, or if it is no longer relevant and instead the links to the content need to be removed (or if any/all of these represent any sort of blocker to launch).

These are all pages that were not part of the original scope and sitemaps for the new site. 

We're very happy to migrate any of these if it would help; there should be enough time under the retainer. 

- [ ] VMF (https://www.doi.org/VMF/index.html)
- [ ] DOI logo download page (https://www.doi.org/logo.html)
- [ ] Document Archive (https://www.doi.org/publications.html)
- [ ] Tools page (https://www.doi.org/tools.html)
- [x] DOI Kernel XML Schema (https://www.doi.org/doi_handbook/DOI_Schema_Release_Notes.html)
- [x] DOI Kernel XML Schema Policy (https://www.doi.org/doi_handbook/DOI_Schema_Policy_Notes.html)
- [x] DOI Data Dictionary (https://www.doi.org/doi_handbook/schemas/dd/intro.html)

**Comment by cazinc** [comment]
Both the DOI Kernel XML and the DOI Data Dictionary pages need migrated for launch, will assign to @cazinc

**Comment by cazinc** [comment]
@JonathanClarkDOIF the remaining pages above (VMF, DOI logo, Docs Archive, Tools) will need to be "unlinked" from copy in the sense that any mentions of them need to be deleted from existing content or replaced with explanatory copy about why these pages no longer exist. I'll leave this with you. The easiest way to find these mentions is probably to just search through the whole site (in your Editor) looking for "VMF" or "Tools" for example.

**Comment by JonathanClarkDOIF** [comment]
Thanks @cazinc  I've found more pages / content that needs migration - how best to deal with this?  I can collect and create an Issue?

**Comment by cazinc** [comment]
Yes I think add them to that other issue where you'd linked to the 3 schemas (#22) or start a new issue.

**Comment by JonathanClarkDOIF** [comment]
Yes
 I do need to look at the document archive (lots of broken links or links to hidden PDFs), create a page in resources and then migrate the links, I'll create a new issue
