### ISSUE TITLE
CNRI HTML templates

### ISSUE THREAD

**Issue by bcgwebdesign** [doi-foundation/doi-website#20]
I have created 2 HTML templates based on new site which can be used for other purposes on other domains. They might need the full URL of the stylesheet set and maybe any graphical assets that are embedded. 
Otherwise just use as is.

They do not get rebuilt with a hugo build on the new site as they are a static resource.

You can view them here
https://staging.doi.org/resources/template_doi_found.html
and
https://staging.doi.org/resources/template_doi_not_found.html

**Comment by cazinc** [comment]
@bcgwebdesign I'm not aware if your CNRI contact(s) are on this board, but if so can you @name them to let them know these are available, or perhaps just pass to them directly via Slack as I think that's how you've spoken in the past?

**Comment by JonathanClarkDOIF** [comment]
Larry just confirmed that Robert has seen this

**Comment by cazinc** [comment]
Ah great, thanks @JonathanClarkDOIF - @bcgwebdesign must have released to him directly first. My mistake.

**Comment by ynnig** [comment]
can this be closed @ilittle-cnri and @cazinc ?

**Comment by ilittle-cnri** [comment]
Yes I believe so.
