### ISSUE TITLE
Pages to be Migrated

### ISSUE THREAD

**Issue by amillercap35** [doi-foundation/doi-website#22]
- [x]  DOI Kernel XML Schema (https://www.doi.org/doi_handbook/DOI_Schema_Release_Notes.html)

- [x]  DOI Kernel XML Schema Policy (https://www.doi.org/doi_handbook/DOI_Schema_Policy_Notes.html) 

- [x] DOI Data Dictionary (https://www.doi.org/doi_handbook/schemas/dd/intro.html)

**Comment by cazinc** [comment]
This is now complete. See 

- DOI Kernel XML Schema: http://localhost:1313/the-identifier/resources/handbook/doi_kernel_xml_schema/
- DOI Kernel XML Schema Policy: http://localhost:1313/the-identifier/resources/handbook/doi_kernel_xml_schema_policy_notes/
- DOI Data Dictionary: http://localhost:1313/the-identifier/resources/handbook/doi_data_dictionary/

On the Data Dictionary we've just brought over the raw HTML of the dictionary itself, which comprised of about 550 pages. This could perhaps be migrated into a new-look template, or rebuilt in some way, after launch.

**Comment by cazinc** [comment]
I've just migrated the first 2 links Jonathan. The third one - https://github.com/doi-foundation/doi-website/issues/doi.org/doi_schemas/iso3166a2.xsd - is giving me a 404. Can you provide an updated URL?

**Comment by JonathanClarkDOIF** [comment]
https://www.doi.org/doi_schemas/iso3166a2.xsd

**Comment by cazinc** [comment]
Great, thanks for that. Now migrated: https://staging.doi.org/doi_schemas/iso3166a2.xsd
